apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd
  labels:
    app.kubernetes.io/name: tusd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: tusd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tusd
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9095'
    spec:
      containers:
      - name: tusd
        image: "resumable-upload/tusd:0.0.1"
        imagePullPolicy: IfNotPresent
        args:
          - "-host"
          - "0.0.0.0"
          - "-port"
          - "1080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /
              port: http
        readinessProbe:
            httpGet:
              path: /
              port: http
        ports:
            - name: http
              containerPort: 1080
              protocol: TCP

        securityContext:
          readOnlyRootFilesystem: false
        volumeMounts:
          - name: tusd
            mountPath: /data
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - tusd
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - tusd
                topologyKey: "failure-domain.beta.kubernetes.io/zone"
      securityContext:
        runAsUser: 1000
        fsGroup: 10000
      serviceAccountName: tf-resumable-upload
      volumes:
        - name: tusd
          emptyDir: {}
