apiVersion: v1
kind: Service
metadata:
  name: tusd
  labels:
    app.kubernetes.io/name: tusd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 1080
      targetPort: http
      protocol: TCP
      appProtocol: http
  selector:
    app.kubernetes.io/name: tusd
