apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localstack
  labels:
    app.kubernetes.io/name: localstack
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: localstack
roleRef:
  kind: Role
  name: localstack
  apiGroup: rbac.authorization.k8s.io