apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: localstack
  labels:
    app.kubernetes.io/name: localstack
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["*"]