apiVersion: v1
kind: Service
metadata:
  name: tusd-n
  labels:
    app: tusd-n
spec:
  type: NodePort
  ports:
    - name: http
      port: 1080
      targetPort: "http"
      protocol: TCP
      nodePort: 30950
  selector:
    app.kubernetes.io/name: tusd
